id: section-products
title: My Handmade Creations
description:
  Explore a collection of unique crochet creations, from adorable amigurumi to stylish accessories, all crafted with love and creativity.
items:
  - id: barnabe
    image: img/creations/barnabe.png
    caption: |
      🐋💙 Meet Barnabé the Whale! With his soft curves and friendly face, he's the perfect
      ocean companion and such a joy to bring to life in yarn.
    links:
      - id: youtube
        label: Watch on YouTube Free Barnabe Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRQRQnMb4I5YVDqn7hAuH9bD
        icon: "i-simple-icons-youtube"
        target: _blank
      - id: etsy
        label: Buy Community-Tested Barnabe Pattern on Etsy
        to: https://www.etsy.com/ca/listing/4298995429/barnabe-the-whale-crochet-pattern
        icon: i-simple-icons-etsy
        target: _blank
  - id: shelly
    image: img/creations/shelly.png
    caption: |
      ✨ Shelly the Turtle is here! 🐢✨ With her sweet little shell and gentle personality,
      she's a fun and relaxing project to make, and turns into an adorable companion that's
      perfect for gifting or keeping as your own handmade treasure. 💚
    links:
      - id: youtube
        label: Watch on YouTube Free Shelly Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRR4SiP_p02lQgck-HYhPoDL
        icon: i-simple-icons-youtube
        target: _blank
      - id: etsy
        label: Buy Community-Tested Shelly Pattern on Etsy
        to: https://www.etsy.com/ca/listing/1906170787/shelly-the-turtle-crochet-pattern
        icon: i-simple-icons-etsy
        target: _blank

  - id: kevin
    image: img/creations/kevin.png
    caption: |
      🐥 Kevin is the most versatile little friend — depending on your colors and mood,
      he can be a goose, a canary, or a chick, always bringing charm and smiles!
    links:
      - id: youtube
        label: Watch on YouTube Free Kevin Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRSsAHtqY3_f_doZsJ80vPq3
        icon: i-simple-icons-youtube
        target: _blank
      - id: etsy
        label: Buy Community-Tested Kevin Pattern on Etsy
        to: https://www.etsy.com/ca/listing/4302012705/kevin-the-chick-crochet-pattern
        icon: i-simple-icons-etsy
        target: _blank

  - id: lola
    image: img/creations/lola.png
    caption: |
      ✨ Lola the Owl shines in every version — bold, pastel, cotton, or plush — each one
      bursting with personality and unique charm, especially with all those creative eyes! 😍
    links:
      - id: youtube
        label: Watch on YouTube Free Lola Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRS7K30oQd2T6XRMmtDDqv3x
        icon: i-simple-icons-youtube
        target: _blank
      - id: etsy
        label: Buy Community-Tested Lola Pattern on Etsy
        to: https://www.etsy.com/ca/listing/4305832049/lola-the-owl-crochet-pattern-amigurumi
        icon: i-simple-icons-etsy
        target: _blank

  - id: lenny
    image: img/creations/lenny.png
    caption: |
      🎉 Lenny the Octopus may take patience with his 8 legs, but the reward is a playful,
      cuddly sea creature that's full of character and worth every stitch! 🐙😍
    links:
      - id: youtube
        label: Watch on YouTube Free Lenny Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRT72jx-hwmkWj4tzW70HHl2
        icon: i-simple-icons-youtube
        target: _blank
      - id: etsy
        label: Buy Community-Tested Lenny Pattern on Etsy
        to: https://www.etsy.com/ca/listing/4313034236/lenny-the-octopus-crochet-pattern
        icon: i-simple-icons-etsy
        target: _blank

  - id: roxanne
    image: img/creations/roxanne.png
    caption: |
      🦊 Roxanne the Red Panda is playful and vibrant, with fun color changes that challenge
      your skills and reward you with a stunning little friend full of charm. 😍
    links:
      - id: youtube
        label: Watch on YouTube Free Roxanne Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRQvdlueYWQKGjWww6L0dVgX
        icon: i-simple-icons-youtube
        target: _blank
      - id: etsy
        label: Buy Community-Tested Roxanne Pattern on Etsy
        to: https://www.etsy.com/ca/listing/4323125630/roxanne-the-red-panda-crochet-pattern
        icon: i-simple-icons-etsy
        target: _blank

  - id: marcus
    image: img/creations/marcus.png
    caption: |
      🐘 Marcus the Elephant is a gentle giant who looks amazing in any shade, from soft pastels
      to bold colors, each version carrying its own sweet and whimsical personality. 💜
    links:
      - id: youtube
        label: Watch on YouTube Free Marcus Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRRWvUSDBKvoeGKU0c1oP6qi
        icon: i-simple-icons-youtube
        target: _blank
      - id: etsy
        label: Buy Community-Tested Marcus Pattern on Etsy
        to: https://www.etsy.com/ca/listing/4330248020/marcus-the-elephant-crochet-pattern
        icon: i-simple-icons-etsy
        target: _blank

  - id: kimmie
    image: img/creations/kimmie.png
    caption: |
      🐭 Kimmie the Mouse can be fluffy and realistic, colorful and playful, or anything in between,
      always transforming into an adorable little companion full of charm. ✨
    links:
      - id: youtube
        label: Watch on YouTube Free Kimmie Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRRWNE95ZzgA0mHM2_5kQSZw
        icon: i-simple-icons-youtube
        target: _blank
      - id: etsy
        label: Buy Community-Tested Kimmie Pattern on Etsy
        to: https://www.etsy.com/ca/listing/4338959771/kimmie-the-mouse-crochet-pattern
        icon: i-simple-icons-etsy
        target: _blank

  - id: gordon
    image: img/creations/gordon.png
    caption: |
      🐷 Gordon the Pig is endlessly fun, whether he's a spooky zombie, a Frankenstein creature,
      or a classic pink piggy — every version shows off his quirky and lovable personality. 💕
    links:
      - id: youtube
        label: Watch on YouTube Free Gordon Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRTMkuOIa5O50oAVetU_X1mT
        icon: i-simple-icons-youtube
        target: _blank
      - id: etsy
        label: Buy Community-Tested Gordon Pattern on Etsy
        to: https://www.etsy.com/ca/listing/4347606426/gordon-the-pig-crochet-pattern-amigurumi
        icon: i-simple-icons-etsy
        target: _blank

  - id: ezra
    image: img/creations/ezra.png
    caption: |
      🐉 Ezra the Dragon is magical in every shade — from fiery reds to icy blues, pastel dreams
      to grumpy expressions — he's always a showstopper with unique personality. ✨
    links:
      - id: youtube
        label: Watch on YouTube Free Ezra Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRQlycAWBNGkiX1Lq7ptZH7k
        icon: i-simple-icons-youtube
        target: _blank
      - id: etsy
        label: Buy Community-Tested Ezra Pattern on Etsy
        to: https://www.etsy.com/ca/listing/4357214323/ezra-the-dragon-crochet-pattern
        icon: i-simple-icons-etsy
        target: _blank

  - id: kissy
    image: img/creations/kissy.png
    caption: |
      🦇 Kissy the Bat is cute in every style — classic black, colorful pastels, embroidered eyes,
      or oversized safety eyes — she always brings her own unique, lovable charm. 🥰
    links:
      - id: youtube
        label: Watch on YouTube Free Kissy Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRRD47cUAJbSJif8itcgeNgd
        icon: i-simple-icons-youtube
        target: _blank
      - id: etsy
        label: Buy Community-Tested Kissy Pattern on Etsy
        to: https://www.etsy.com/ca/listing/4362532379/kissy-the-bat-crochet-pattern-amigurumi
        icon: i-simple-icons-etsy
        target: _blank

  - id: andy
    image: img/creations/andy.png
    caption: |
      🎃 Andy the Creature is spooky, quirky, and full of personality with his mismatched eyes,
      making him a perfect Halloween friend or a unique companion all year round! 🧟
    links:
      - id: youtube
        label: Watch on YouTube Free Andy Pattern Playlist
        to: https://www.youtube.com/playlist?list=PL8tgm60WDRRQbkxReUcxPt6PoYzFBmr0t
        icon: i-simple-icons-youtube
        target: _blank
      - id: etsy
        label: Buy Community-Tested Andy Pattern on Etsy
        to: https://www.etsy.com/ca/listing/4369278765/andy-the-creature-monster-crochet
        icon: i-simple-icons-etsy
        target: _blank
